version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - partystream-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - partystream-network

networks:
  partystream-network:
    driver: bridge
